export const CourseList = [
    {
      author: "Author 1",
      banner: "https://via.placeholder.com/150",
      chapter: [
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "Python Chapter 1" },
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "Python Chapter 2" },
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "Python Chapter 3" },
      ],
      demourl: "https://www.w3schools.com/html/mov_bbb.mp4",
      description: "Learn Python from scratch.",
      free: true,
      id: 1,
      name: "Python",
      sourcecode: "https://github.com/author/course1",
      tags: ["python", "programming"],
      totalchapters: 3,
    },
    {
      author: "Author 2",
      banner: "https://via.placeholder.com/150",
      chapter: [
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "React Native Chapter 1" },
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "React Native Chapter 2" },
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "React Native Chapter 3" },
      ],
      demourl: "https://www.w3schools.com/html/mov_bbb.mp4",
      description: "Learn React Native to build mobile apps.",
      free: true,
      id: 2,
      name: "React Native",
      sourcecode: "https://github.com/author/course2",
      tags: ["react-native", "mobile development"],
      totalchapters: 3,
    },
    {
      author: "Author 3",
      banner: "https://via.placeholder.com/150",
      chapter: [
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "JavaScript Chapter 1" },
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "JavaScript Chapter 2" },
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "JavaScript Chapter 3" },
      ],
      demourl: "https://www.w3schools.com/html/mov_bbb.mp4",
      description: "Master JavaScript for web development.",
      free: true,
      id: 3,
      name: "JavaScript",
      sourcecode: "https://github.com/author/course3",
      tags: ["javascript", "web development"],
      totalchapters: 3,
    },
    {
      author: "Author 4",
      banner: "https://via.placeholder.com/150",
      chapter: [
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "HTML & CSS Chapter 1" },
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "HTML & CSS Chapter 2" },
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "HTML & CSS Chapter 3" },
      ],
      demourl: "https://www.w3schools.com/html/mov_bbb.mp4",
      description: "Build beautiful websites with HTML & CSS.",
      free: true,
      id: 4,
      name: "HTML & CSS",
      sourcecode: "https://github.com/author/course4",
      tags: ["html", "css", "web design"],
      totalchapters: 3,
    },
    {
      author: "Author 5",
      banner: "https://via.placeholder.com/150",
      chapter: [
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "Data Science Chapter 1" },
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "Data Science Chapter 2" },
        { url: "https://www.w3schools.com/html/mov_bbb.mp4", name: "Data Science Chapter 3" },
      ],
      demourl: "https://www.w3schools.com/html/mov_bbb.mp4",
      description: "Introduction to Data Science.",
      free: true,
      id: 5,
      name: "Data Science",
      sourcecode: "https://github.com/author/course5",
      tags: ["data science", "analytics"],
      totalchapters: 3,
    }
  ];
  

